from python:3.9.6-slim-buster
ENV TZ Asia/Shanghai
EXPOSE 5000

COPY index.py requirements.txt vegetable_model_v2.h5 /app/
WORKDIR /app/

RUN pip install -r requirements.txt -i https://pypi.douban.com/simple

ENTRYPOINT python index.py
